# Extracting 
We've extracted two datasets from kaggle, one containing 2018 FIFA world cup data on the national squads, and another with data on soccer players from major leagues in the world.

In [24]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

# Transform

We've used pandas to get input csv files, create dataframes, and clean the data.

In [2]:
# wc csv file path
csv_wc = "data/2018FIFAWC.csv"

# create wc squads df 
wc_df = pd.read_csv(csv_wc)
wc_df["Player"] = wc_df["Player"].map(lambda x: x.rstrip('(captain)'))
wc_df = wc_df.drop(columns=["Player Count"])
wc_df = wc_df.rename(columns={"Player":"Name"})
wc_df.head()

,Team,Group,Squad Number,Position,Name,Date Of Birth,Age,Caps,Goals,Club
0,Egypt,A,1,GK,Essam El-Hadary,1973/01/15,45,157,0,Al-Taawoun
1,Egypt,A,2,DF,Ali Gabr,1989/01/01,29,20,1,West Bromwich Albion
2,Egypt,A,3,DF,Ahmed Elmohamady,1987/09/09,30,77,2,Aston Villa
3,Egypt,A,4,MF,Omar Gaber,1992/01/30,26,23,0,Los Angeles FC
4,Egypt,A,5,MF,Sam Morsy,1991/09/10,26,4,0,Wigan Athletic

In [19]:
# players csv file path
csv_players = "data/players.csv"

# create players df
players_df = pd.read_csv(csv_players)
players_df = players_df.dropna()
players_df[["National_Kit","Club_Kit","Contract_Expiry"]] = players_df[["National_Kit","Club_Kit","Contract_Expiry"]].astype(int)
players_df["Height"] = players_df["Height"].map(lambda x: x.rstrip('cm'))
players_df["Weight"] = players_df["Weight"].map(lambda x: x.rstrip('kg'))
players_df = players_df.rename(columns={"Height":"Height(cm)","Weight":"Weight(kg)"})
players_df.head()

,Name,Nationality,National_Position,National_Kit,Club,Club_Position,Club_Kit,Club_Joining,Contract_Expiry,Rating,...,Long_Shots,Curve,Freekick_Accuracy,Penalties,Volleys,GK_Positioning,GK_Diving,GK_Kicking,GK_Handling,GK_Reflexes
0,Cristiano Ronaldo,Portugal,LS,7,Real Madrid,LW,7,07/01/2009,2021,94,...,90,81,76,85,88,14,7,15,11,11
1,Lionel Messi,Argentina,RW,10,FC Barcelona,RW,10,07/01/2004,2018,93,...,88,89,90,74,85,14,6,15,11,8
2,Neymar,Brazil,LW,10,FC Barcelona,LW,11,07/01/2013,2021,92,...,77,79,84,81,83,15,9,15,9,11
3,Luis Su√°rez,Uruguay,LS,9,FC Barcelona,ST,9,07/11/2014,2021,92,...,86,86,84,85,88,33,27,31,25,37
4,Manuel Neuer,Germany,GK,1,FC Bayern,GK,1,07/01/2011,2021,92,...,16,14,11,47,11,91,89,95,90,89

In [23]:
columns_to_drop = [
    'Work_Rate', 'Weak_foot', 'Skill_Moves',
    'Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle',
    'Standing_Tackle', 'Aggression', 'Reactions', 'Attacking_Position',
    'Interceptions', 'Vision', 'Composure', 'Crossing', 'Short_Pass',
    'Long_Pass', 'Acceleration', 'Speed', 'Stamina', 'Strength', 'Balance',
    'Agility', 'Jumping', 'Heading', 'Shot_Power', 'Finishing',
    'Long_Shots', 'Curve', 'Freekick_Accuracy', 'Penalties', 'Volleys',
    'GK_Positioning', 'GK_Diving', 'GK_Kicking', 'GK_Handling',
    'GK_Reflexes'
]

# players_df = players_df.drop(columns=columns_to_drop)
players_df.head()

,Name,Nationality,National_Position,National_Kit,Club,Club_Position,Club_Kit,Club_Joining,Contract_Expiry,Rating,Height(cm),Weight(kg),Preffered_Foot,Birth_Date,Age,Preffered_Position
0,Cristiano Ronaldo,Portugal,LS,7,Real Madrid,LW,7,07/01/2009,2021,94,185,80,Right,02/05/1985,32,LW/ST
1,Lionel Messi,Argentina,RW,10,FC Barcelona,RW,10,07/01/2004,2018,93,170,72,Left,06/24/1987,29,RW
2,Neymar,Brazil,LW,10,FC Barcelona,LW,11,07/01/2013,2021,92,174,68,Right,02/05/1992,25,LW
3,Luis Su√°rez,Uruguay,LS,9,FC Barcelona,ST,9,07/11/2014,2021,92,182,85,Right,01/24/1987,30,ST
4,Manuel Neuer,Germany,GK,1,FC Bayern,GK,1,07/01/2011,2021,92,193,92,Right,03/27/1986,31,GK

In [13]:
players_df["National_Kit"] = players_df["National_Kit"].astype(int)
players_df.head()

,Name,Nationality,National_Position,National_Kit,Club,Club_Position,Club_Kit,Club_Joining,Contract_Expiry,Rating,Height,Weight,Preffered_Foot,Birth_Date,Age,Preffered_Position
0,Cristiano Ronaldo,Portugal,LS,7,Real Madrid,LW,7.0,07/01/2009,2021.0,94,185 cm,80 kg,Right,02/05/1985,32,LW/ST
1,Lionel Messi,Argentina,RW,10,FC Barcelona,RW,10.0,07/01/2004,2018.0,93,170 cm,72 kg,Left,06/24/1987,29,RW
2,Neymar,Brazil,LW,10,FC Barcelona,LW,11.0,07/01/2013,2021.0,92,174 cm,68 kg,Right,02/05/1992,25,LW
3,Luis Su√°rez,Uruguay,LS,9,FC Barcelona,ST,9.0,07/11/2014,2021.0,92,182 cm,85 kg,Right,01/24/1987,30,ST
4,Manuel Neuer,Germany,GK,1,FC Bayern,GK,1.0,07/01/2011,2021.0,92,193 cm,92 kg,Right,03/27/1986,31,GK

# Load
We've used sqlalchemy and pymysql to load our cleaned dataframes to our production database.

In [ ]:
# create connection to db
connection_string = "root:root@127.0.0.1/soccer_data"
engine = create_engine("mysql://{}".format(connection_string))

In [ ]:
# create table for wc data
wc_df.to_sql(name='wc_squads', con=engine, if_exists='append', index=False)

In [ ]:
# create table for players data
players_df.to_sql(name='players', con=engine, if_exists='append', index=False)

In [ ]:
# confirm wc table has been added
# pd.read_sql_query('select * from wc_squads', con=engine).head()

In [ ]:
# confirm players table has been added
# pd.read_sql_query('select * from players', con=engine).head()